services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__DefaultConnection: Host=db;Port=5432;Database=tms_dev;Username=tms;Password=tms_pass
    ports:
      - "5044:8080"
    restart: on-failure

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: tms_dev
      POSTGRES_PASSWORD: tms_pass
      POSTGRES_USER: tms
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U tms -d tms_dev"]
      interval: 5s
      timeout: 5s
      retries: 10
      start_period: 10s
    ports:
      - "5432:5432"
    restart: unless-stopped
    volumes:
      - db-data:/var/lib/postgresql/data

volumes:
  db-data:
